name: my_first_app_lotto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png
    - assets/logo.png
    - assets/icon.png   # Ikon fájl

# Splash screen beállítás
flutter_native_splash:
  color: "#FFFFFF"            # Splash háttérszín
  image: assets/splash_logo.png
  android: true
  ios: true
  android_gravity: center

# Ikon beállítás
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png
