name: Android Release to Firebase

on:
  release:
    types: [published]

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK (release)
        run: flutter build apk --release

      - name: List APK files
        run: ls -R build/app/outputs/

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

            - name: Distribute to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID_ANDROID }} \
            --groups testers \
            --release-notes "GitHub Release: ${{ github.event.release.tag_name }} - ${{ github.event.release.name }}"

