      - name: Write google-services.json (simple)
        env:
          GOOGLE_JSON: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}
        run: |
          set -e
          mkdir -p android/app
          # írd ki NYERSEN a secret tartalmát – mindegy, hogy egy sor vagy több sor
          printf '%s' "$GOOGLE_JSON" > android/app/google-services.json
          test -s android/app/google-services.json || (echo "google-services.json is empty" && exit 1)
          head -c 1 android/app/google-services.json | grep '{' >/dev/null || (echo "not JSON (no starting '{')" && exit 1)

      - name: Validate google-services.json + package name
        run: |
          python - <<'PY'
          import json, sys
          p = "android/app/google-services.json"
          with open(p, "r", encoding="utf-8") as f:
              data = json.load(f)
          assert isinstance(data, dict), "Root is not a JSON object"
          assert "client" in data and data["client"], "Missing 'client' array"
          pkg = None
          for c in data["client"]:
              ai = c.get("client_info", {}).get("android_client_info", {})
              if "package_name" in ai:
                  pkg = ai["package_name"]; break
          assert pkg, "package_name not found in JSON"
          expected = "com.histvan86.my_first_app_lotto"
          assert pkg == expected, f"package mismatch: {pkg} != {expected}"
          print("google-services.json OK for", pkg)
          PY
