- name: Verify Groovy build.gradle exists (no .kts)
  run: |
    if [ ! -f android/app/build.gradle ]; then
      echo "ERROR: Missing android/app/build.gradle (Groovy)."
      exit 1
    fi
    if [ -f android/app/build.gradle.kts ]; then
      echo "ERROR: build.gradle.kts still exists, delete it."
      exit 1
    fi
    echo "OK: Groovy build.gradle present, no .kts found."
